---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: memcached-operator-manager-role
rules:
- apiGroups:
  - cache.example.com
  - apps
  resources:
  - memcacheds
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  - apps
  resources:
  - memcacheds/finalizers
  - deployments
  verbs:
  - update
- apiGroups:
  - cache.example.com
  - apps
  resources:
  - memcacheds/status
  - deployments
  verbs:
  - get
  - patch
  - update
