apiVersion: v1
kind: Namespace
metadata:
  name: my-mariadb-operator-app
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: my-mariadb-operator-app
spec:
  targetNamespaces:
  - my-mariadb-operator-app
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-mariadb-operator-app
  namespace: my-mariadb-operator-app
spec:
  channel: alpha
  name: mariadb-operator-app
  source: operatorhubio-catalog
  sourceNamespace: olm